pybb/contrib/ban/urls.py
from django.conf.urls import url

from .views import (BanCreateView, BanListView,
                    BanDeleteView)


urlpatterns = [
    url('^ban/(?P<username>[^/]+)/create/$',
        BanCreateView.as_view(),
        name='ban_create'),

    url('^ban/(?P<username>[^/]+)/delete/$',
        BanDeleteView.as_view(),
        name='ban_delete'),

    url('^ban/list/$',
        BanListView.as_view(),
        name='ban_list'),
]

pybb/contrib/quotes/urls.py
from django.conf.urls import url

from .views import QuoteView


urlpatterns = [
    url('^post/quote/$',
        QuoteView.as_view(),
        name='quote'),
]

pybb/contrib/reports/urls.py
from django.conf.urls import url

from .views import (ReportCreateView, ReportListView,
                    ReportDetailView, ReportCloseView)


urlpatterns = [
    url('^reports/(?P<pk>\d+)/create/$',
        ReportCreateView.as_view(),
        name='report_create'),
    url('^reports/(?P<pk>\d+)/detail/$',
        ReportDetailView.as_view(),
        name='report_detail'),
    url('^reports/(?P<pk>\d+)/close/$',
        ReportCloseView.as_view(),
        name='report_close'),
    url('^reports/list/$',
        ReportListView.as_view(),
        name='report_list'),
]

pybb/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from pybb import defaults, views, feeds


app_name = "pybb"


urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$',
        feeds.LastPosts(),
        name='feed_posts'),

    url('^feeds/topics/$',
        feeds.LastTopics(),
        name='feed_topics'),

    url('^$',
        views.IndexView.as_view(),
        name='index'),

    url('^forums/(?:(?P<forum_id>\d+)/)?forums/create/$',
        views.ForumCreateView.as_view(),
        name='forum_create'),

    url('^forums/(?P<pk>\d+)/moderators/$',
        views.ModeratorListView.as_view(),
        name='moderator_list'),
    url('^forums/(?P<forum_id>\d+)/moderators/(?P<moderator_id>\d+)$',
        views.ModeratorDetailView.as_view(),
        name='moderator_detail'),
    url('^forums/(?P<forum_id>\d+)/moderators/(?P<moderator_id>\d+)/delete/$',
        views.ModeratorDeleteView.as_view(),
        name='moderator_delete'),
    url('^forums/(?P<forum_id>\d+)/moderators/create/$',
        views.ModeratorCreateView.as_view(),
        name='moderator_create'),
    url('^forums/update/(?P<pk>\d+)/$',
        views.ForumUpdateView.as_view(),
        name='forum_update'),

    url('^topics/(?P<pk>\d+)/stick/$',
        views.TopicStickView.as_view(),
        name='topic_stick'),
    url('^topics/(?P<pk>\d+)/unstick/$',
        views.TopicUnstickView.as_view(),
        name='topic_unstick'),
    url('^topics/(?P<pk>\d+)/close/$',
        views.TopicCloseView.as_view(),
        name='topic_close'),
    url('^topics/(?P<pk>\d+)/open/$',
        views.TopicOpenView.as_view(),
        name='topic_open'),
    url('^topics/merge/$',
        views.TopicMergeView.as_view(),
        name='topic_merge'),
    url('^topics/move/$',
        views.TopicMoveView.as_view(),
        name='topic_move'),
    url('^topics/(?P<pk>\d+)/delete/$',
        views.TopicDeleteView.as_view(),
        name='topic_delete'),
    url('^topics/delete/$',
        views.TopicsDeleteView.as_view(),
        name='topics_delete'),
    url('^topics/(?P<pk>\d+)/poll-vote/$',
        views.TopicPollVoteView.as_view(),
        name='topic_poll_vote'),

    # Add topic/post
    url('^forums/(?:(?P<forum_id>\d+)/)?topic/add/$',
        views.PostCreateView.as_view(),
        name='topic_create'),
    url('^topics/post/add/$',
        views.PostsCreateView.as_view(),
        name='posts_create'),
    url('^topics/(?P<topic_id>\d+)/post/add/$',
        views.PostCreateView.as_view(),
        name='post_create'),
    url('^topics/(?P<topic_id>\d+)/tracker/$',
        views.TopicTrackerRedirectView.as_view(),
        name='topic_tracker_redirect'),
    url('^topics/latest/$',
        views.TopicsLatestView.as_view(),
        name='topics_latest'),

    # Post
    url('^posts/redirect/(?:(?P<post_id>\d+)/)?$',
        views.PostRedirectView.as_view(),
        name='post_redirect'),
    url('^posts/(?P<pk>\d+)/edit/$',
        views.PostUpdateView.as_view(),
        name='post_update'),
    url('^posts/(?P<pk>\d+)/delete/$',
        views.PostDeleteView.as_view(),
        name='post_delete'),
    url('^posts/(?P<pk>\d+)/moderate/$',
        views.PostModerateView.as_view(),
        name='post_moderate'),
    url('^posts/move/$',
        views.PostsMoveView.as_view(),
        name='post_move'),

    # Subscription
    url('^subscriptions/$',
        views.SubscriptionListView.as_view(),
        name='subscription_list'),

    url('^subscription/topic/change/$',
        views.SubscriptionChangeView.as_view(),
        name='subscription_change'),

    url('^subscription/topic/delete/$',
        views.SubscriptionDeleteView.as_view(),
        name='subscription_delete'),

    url('^subscription/topic/add/$',
        views.create_subscription,
        name='subscription_create'),

    url('^post/preview/$',
        views.post_preview,
        name='post_preview'),

    # Commands
    url('^forums/mark-as-read/$',
        views.ForumMarkAsReadView.as_view(),
        name='forum_mark_as_read'),

    url('^moderation/logs/$',
        views.LogModerationListView.as_view(),
        name='logmoderation_list'),

    url('^(?P<username>[\w\-\_]+)/posts/$',
        views.UserPostsView.as_view(),
        name='user_posts'),

    url('^(?P<username>[\w\-\_]+)/posts/delete/$',
        views.UserPostsDeleteView.as_view(),
        name='user_posts_delete'),

    url(views.TopicDetailView.url,
        views.TopicDetailView.as_view(),
        name='topic_detail'),

    url(views.ForumDetailView.url,
        views.ForumDetailView.as_view(),
        name='forum_detail'),
]

if defaults.PYBB_ATTACHMENT_ENABLE:
    urlpatterns += [
        url('^post/attachment/list/$',
            views.AttachmentListView.as_view(),
            name='attachment_list'),

        url('^post/attachment/(?P<pk>\d+)/delete/$',
            views.AttachmentDeleteView.as_view(),
            name='attachment_delete'),
    ]

pybb/contrib/ban/models.py
from django.contrib.auth.models import AnonymousUser

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import signals

from pybb.base import ModelBase, ManagerBase

from .util import get_ip
from . import settings

from pybb.compat import AUTH_USER_MODEL


class BannedUser(ModelBase):
    user = models.OneToOneField(AUTH_USER_MODEL, related_name='banned', on_delete=models.CASCADE)
    reason = models.TextField(_('Reason'), null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'pybb'
        verbose_name = _('Banned user')
        verbose_name_plural = _('Banned users')

    def __str__(self):
        return _('User %(user)s banned for %(reason)s') % {
            'user': self.user,
            'reason': self.reason
        }


class IPAddressManager(ManagerBase):
    def register(self, user, ip_address):
        params = {
            'user': user,
            'ip_address': ip_address
        }

        try:
            ip = self.model.objects.filter(**params)[0]
        except IndexError:
            ip = self.model.objects.create(**params)

        return ip


class IPAddress(ModelBase):
    user = models.ForeignKey(AUTH_USER_MODEL,
                             related_name='ip_addresses',
                             null=True, blank=True, on_delete=models.SET(AnonymousUser))
    ip_address = models.IPAddressField(_('IP Address'),
                                       help_text=_('The IP address'))

    banned = models.BooleanField(default=False, db_index=True)

    objects = IPAddressManager()

    class Meta:
        app_label = 'pybb'
        verbose_name = _('IP')
        verbose_name_plural = _('IPs')

    def __str__(self):
        return self.ip_address


def handle_user_logged_in(sender, request, user, **kwargs):
    from pybb.compat import get_user_model

    User = get_user_model()

    try:
        BannedUser.objects.get(user=user)
    except BannedUser.DoesNotExist:
        value = request.COOKIES.get(settings.PYBB_BAN_COOKIE_NAME, None)

        banned_user = None

        if value:
            try:
                existing_user = User.objects.get(pk=int(value))
            except (User.DoesNotExist, ValueError):
                banned_user = BannedUser(user=user,
                                         reason=_('Cookie exists: user already banned from anonymous account'))
            else:
                banned_user = BannedUser(user=user,
                                         reason=_('Cookie exists: user already banned for the account %s') % existing_user)

        ip_address = get_ip(request)

        exists = IPAddress.objects.filter(ip_address=ip_address, banned=True).exists()

        if exists:
            banned_user = BannedUser(user=user,
                                     reason=_('IP Address %s is banned') % ip_address)

        if banned_user:
            banned_user.save()


from django.apps import apps

if apps.ready:
    from .compat import User

    signals.user_logged_in.connect(handle_user_logged_in, sender=User)

pybb/contrib/mentions/models.py
from collections import defaultdict

from django.contrib.auth.models import AnonymousUser
from django.db import models
from django.db.models import signals
from django.utils.translation import gettext_lazy as _

from pybb.models import Post
from pybb.compat import AUTH_USER_MODEL
from pybb.base import ModelBase, ManagerBase

from .signals import mentioned


class MentionManager(ManagerBase):
    def __init__(self, *args, **kwargs):
        super(MentionManager, self).__init__(*args, **kwargs)

        self._registry = defaultdict(list)

    def contribute_to_class(self, cls, name):
        mentioned.connect(self.mentioned)
        signals.post_save.connect(self.post_save, sender=Post)
        return super(MentionManager, self).contribute_to_class(cls, name)

    def mentioned(self, user, post, **kwargs):
        obj = {
            'from_user': post.user,
            'to_user': user,
            'post': post
        }

        self._registry[id(post)].append(obj)

    def post_save(self, instance, **kwargs):
        mentions = self._registry.pop(id(instance), [])

        for mention in mentions:
            mention['post'] = instance

            obj, created = self.model.objects.get_or_create(**mention)


class Mention(ModelBase):
    from_user = models.ForeignKey(AUTH_USER_MODEL, related_name='sent_mentions', on_delete=models.SET(AnonymousUser))
    post = models.ForeignKey(Post, related_name='mentions', on_delete=models.CASCADE)
    to_user = models.ForeignKey(AUTH_USER_MODEL, related_name='received_mentions', on_delete=models.SET(AnonymousUser))
    created = models.DateTimeField(auto_now_add=True)

    objects = MentionManager()

    class Meta:
        app_label = 'pybb'
        verbose_name = _('Mention')
        verbose_name_plural = _('Mentions')

pybb/models/post.py
from pybb.models.base import BasePost, PostManager


class Post(BasePost):
    class Meta(BasePost.Meta):
        abstract = False

    objects = PostManager()

pybb/contrib/ban/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import BannedUser, IPAddress


class BanForm(forms.ModelForm):
    class Meta:
        model = BannedUser
        fields = ('reason',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)

        super(BanForm, self).__init__(*args, **kwargs)

        self.fields['reason'].required = True

        if self.user:
            self.ip_addresses = IPAddress.objects.filter(user=self.user)

            for ip_address in self.ip_addresses:
                self.fields['ip_address_%d' % ip_address.pk] = forms.ChoiceField(
                    label=_('Ban IP Address %s') % ip_address.ip_address,
                    widget=forms.RadioSelect(),
                    choices=(
                        (0, _('No')),
                        (1, _('Yes')),
                    ),
                    initial=0
                )

    def save(self, *args, **kwargs):
        self.instance.user = self.user

        banned = super(BanForm, self).save(*args, **kwargs)

        banned_ips = []

        if self.ip_addresses:
            for ip in self.ip_addresses:
                value = int(self.cleaned_data['ip_address_%d' % ip.pk])

                if value:
                    ip.banned = True
                    ip.save()

                    banned_ips.append(ip)

        return banned, banned_ips

pybb/contrib/profiles/forms.py
import re

from django import forms
from django.utils.translation import ugettext_lazy as _

from pybb import defaults
from pybb.util import get_profile_model


class EditProfileForm(forms.ModelForm):
    class Meta(object):
        model = get_profile_model()
        fields = ('signature', 'time_zone', 'language',
                  'show_signature', 'avatar', )

    signature = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols:': 60}), required=False)

    def clean_avatar(self):
        if self.cleaned_data['avatar'] and (self.cleaned_data['avatar'].size > defaults.PYBB_MAX_AVATAR_SIZE):
            raise forms.ValidationError(_('Avatar is too large, max size: %s bytes') % defaults.PYBB_MAX_AVATAR_SIZE)

        return self.cleaned_data['avatar']

    def clean_signature(self):
        value = self.cleaned_data['signature'].strip()
        if len(re.findall(r'\n', value)) > defaults.PYBB_SIGNATURE_MAX_LINES:
            raise forms.ValidationError(_('Number of lines is limited to %d') % defaults.PYBB_SIGNATURE_MAX_LINES)
        if len(value) > defaults.PYBB_SIGNATURE_MAX_LENGTH:
            raise forms.ValidationError(_('Length of signature is limited to %d') % defaults.PYBB_SIGNATURE_MAX_LENGTH)
        return value

pybb/contrib/reports/forms.py
from .models import Report, ReportMessage

from django import forms


class ReportMessageForm(forms.ModelForm):
    class Meta:
        fields = ('message',)
        model = ReportMessage

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.post = kwargs.pop('post', None)

        super(ReportMessageForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.report, created = Report.objects.get_or_create(post=self.post)
        self.instance.user = self.user

        return super(ReportMessageForm, self).save(*args, **kwargs)

pybb/contrib/ban/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.views.generic.edit import FormMixin
from django.urls import reverse

from pybb.util import generic
from pybb import defaults
from pybb.compat import get_user_model

from .forms import BanForm
from .models import BannedUser, IPAddress

from pure_pagination.paginator import Paginator


class BanCreateView(generic.DetailView, FormMixin):
    slug_url_kwarg = 'username'
    slug_field = 'username'
    form_class = BanForm
    template_name = 'pybb/ban/create.html'

    def get_queryset(self):
        return get_user_model().objects.all()

    def get_form_kwargs(self, **kwargs):
        return dict(super(BanCreateView, self).get_form_kwargs(**kwargs), **{
            'user': self.object
        })

    def get_context_data(self, **kwargs):
        data = super(BanCreateView, self).get_context_data(**kwargs)

        return dict(data, **{
            'form': self.get_form(self.get_form_class()),
        })

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        context = self.get_context_data(object=self.object)

        form = context['form']

        if form.is_valid():
            return self.form_valid(form)

        return self.form_invalid(form)

    def get_success_url(self):
        return reverse('ban_list')

    def form_valid(self, form):
        banned, banned_ips = form.save()

        return redirect(self.get_success_url())

    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BanCreateView, self).dispatch(request, *args, **kwargs)


class BanListView(generic.ListView):
    model = BannedUser
    template_name = 'pybb/ban/list.html'
    context_object_name = 'banned_list'
    paginate_by = defaults.PYBB_TOPIC_PAGE_SIZE
    paginator_class = Paginator

    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BanListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.select_related('user')


class BanDeleteView(generic.DeleteView):
    template_name = 'pybb/ban/delete.html'
    slug_url_kwarg = 'username'
    slug_field = 'user__username'
    model = BannedUser
    context_object_name = 'banned'

    def get_context_data(self, **kwargs):
        return dict(super(BanDeleteView, self).get_context_data(**kwargs), **{
            'ip_addresses': IPAddress.objects.filter(user=self.object.user, banned=True)
        })

    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BanDeleteView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        response = super(BanDeleteView, self).delete(request, *args, **kwargs)

        BannedUser.objects.filter(user=self.object.user).delete()

        IPAddress.objects.filter(user=self.object.user).update(banned=False)

        return response

    def get_success_url(self):
        return reverse('ban_list')

pybb/templates/pybb/post/create.html
{% extends "pybb/base.html" %}
{% load i18n pybb_tags guardian_tags %}

{% block extra_script %}
    {{ block.super }}
    {% include "pybb/_sceditor.html" %}
    <script type="text/javascript" src="{{ STATIC_URL }}pybb/js/jquery.formset.js"></script>
{% endblock %}

{% block breadcrumb %}
    {% if forum %}
        {% with object=forum extra_crumb="New topic" %}
            {% include "pybb/breadcrumb.html" %}
        {% endwith %}
    {% else %}
        {% with object=topic extra_crumb="New reply" %}
            {% include "pybb/breadcrumb.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block content %}

    {% include "pybb/post/form.html" %}

    {% if topic %}
        {% get_obj_perms request.user for topic.forum as "forum_perms" %}

        <div class="topic">
            {% if topic.poll_type != 0 %}
                {% include "pybb/poll/detail.html" %}
            {% endif %}

            <div class="posts">
                {% if first_post %}{% ifnotequal first_post post_list.0 %}
                    {% with first_post as post %}
                        <li class="first_post">{% include "pybb/post/template.html" %}</li>
                    {% endwith %}
                {% endifnotequal %}{% endif %}
                {% for post in post_list %}
                    {% cycle "odd" "even" as rowcolors silent %}
                    {% include "pybb/post/template.html" with page=page_obj %}
                {% endfor %}
            </div>
            <div>&nbsp;</div>
        </div>

        {% if post_count > post_page_size %}
            <hr />
            <div style="text-align: center">
                {% blocktrans with page_size=post_page_size %}This discussion has more {{ page_size }} answers{% endblocktrans %}
                <a href="{{ topic.get_absolute_url }}">{% trans "Click here to see the full discussion" %}</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

pybb/templates/pybb/post/delete.html
{% extends "pybb/base.html" %}
{% load i18n pybb_tags %}

{% block content %}
    <h2>{% trans "Are you sure you want to delete this message?" %}</h2>
    <div class="post-preview well">
        {{ post.body_html|safe }}
    </div>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class="btn" href="{{ post|pybb_post_anchor_url:request.user }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class="btn btn-danger" value="{% trans "Yes, I am sure" %}" />
        </p>
    </form>
{% endblock %}

pybb/templates/pybb/post/form.html
{% load i18n pybb_tags %}
<form class="post-form" action="
    {% if forum %}
        {% url 'pybb:topic_create' forum.pk %}
    {% elif topic %}
        {% url 'pybb:post_create' topic.pk %}
    {% elif not topic and not forum %}
        {% if object %}
            {% url 'pybb:post_update' pk=object.pk %}
        {% else %}
            {% url 'pybb:topic_create' %}
        {% endif %}
    {% endif %}
    " method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }}

        {{ form.hash }}

        {% if form.name %} {{ form.name.errors }} {{ form.name.label_tag }} {{ form.name }} {% endif %}
        {% if form.login %} {{ form.login.errors }} {{ form.login.label_tag }} {{ form.login }}  {% endif %}
        {% if form.body %} {{ form.body.errors }} {{ form.body.label_tag }} {{ form.body }}  {% endif %}

        {% if form.poll_type %}
            {% include "pybb/poll/form.html" %}
        {% endif %}

        <p class="submit">{% include "pybb/_button_submit.html" %}</p>
    </fieldset>
</form>
<div id="attachments-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="attachments-modal-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="attachments-modal-label">{% trans "Attachments" %}</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
        <button class="btn btn-success">{% trans "Save changes" %}</button>
    </div>
</div>

pybb/templates/pybb/post/template.html
{% load i18n pybb_tags thumbnail guardian_tags %}

<a name="post-{{ post.id }}"></a> {# may be remove this string? #}
<table class="table table-bordered post{% if post.on_moderation %} on-moderation{% endif %}{% if post.deleted %}deleted{% endif %}" id="post-{{ post.id }}">
    <thead class="post-header">
    <tr>
    <th colspan="2">

        {% if post.pk %}
            {% if page %}
                <a class="permalink" href="{% url 'pybb:topic_detail' forum_slug=post.topic.forum.slug pk=post.topic.pk slug=post.topic.slug page=page.number %}#post{{ post.pk }}">#</a>
            {% else %}
                <a class="permalink" href="{{ post|pybb_post_anchor_url:request.user }}">#</a>
            {% endif %}
        {% endif %}


        <span class="updated">{% pybb_time post.created %}</span>
    </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="post-info">
            {% include "pybb/avatar.html" %}
            <div class="post-author"><a href="{{ post.user.get_absolute_url }}">{{ post.user.username }}</a></div>

            {% if user.is_superuser or user.is_staff or "can_see_user_ip" in forum_perms %}
                <div class="post-extra-info">{{ post.user_ip }}</div>
            {% endif %}

            {% if post.pk %}
                <div class="post-controls">
                    {% if user.is_moderator and "can_change_post" in forum_perms or post|pybb_posted_by:user %}
                        <a href="{% url 'pybb:post_update' pk=post.id %}">{% trans "Edit" %}</a>
                    {% endif %}

                    {% if user.is_moderator %}
                        {% if "can_delete_post" in forum_perms %}
                            <a href="{% url 'pybb:post_delete' post.id %}">{% trans "Delete" %}</a>
                        {% endif %}

                        {% if post.on_moderation %}
                            <a href="{% url 'pybb:post_moderate' pk=post.id %}">{% trans "Approve post" %}</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endif %}

        </td>
        <td class="post-content">
            {{ post.body_html|safe }}

            {% if post.updated %}
                <div class="updated-message">{% trans "Edited" %} {% pybb_time post.updated %}</div>
            {% endif %}

            {% if post.pk %}
                <div class="post-related">
                    <a href="{% url 'pybb:post_create' topic.id %}?quote_id={{ post.id }}">{% trans "quote" %}</a>

                    <div class='attachments'>
                        {% for attachment in post.attachments.all %}
                            <a href="{{ attachment.file.url }}"><img src="{{ STATIC_URL }}pybb/img/attachment.png"> {{ attachment.size_display }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </td>
    </tr>
    </tbody>
</table>

pybb/templates/pybb/post/update.html
{% extends 'pybb/base.html' %}
{% load pybb_tags i18n %}

{% block title %}{% trans "Editing the post" %}{% endblock title %}

{% block extra_script %}
    {{ block.super }}
    {% include "pybb/_sceditor.html" %}
    <script type="text/javascript" src="{{ STATIC_URL }}pybb/js/jquery.formset.js"></script>
{% endblock %}

{% block content %}
    <h2>{% trans "Editing the post" %}</h2>
    {% include "pybb/post/form.html" %}
{% endblock content %}

{% block breadcrumb %}
    {% with extra_crumb="Edit post" %}
        {% include "pybb/breadcrumb.html" %}
    {% endwith %}
{% endblock %}